export const EXERCISE_LIST_REQUEST = 'EXERCISE_LIST_REQUEST';
export const EXERCISE_LIST_SUCCESS = 'EXERCISE_LIST_SUCCESS';
export const EXERCISE_LIST_FAIL = 'EXERCISE_LIST_FAIL';

export const EXERCISE_DETAILS_SUCCESS = 'EXERCISE_DETAILS_SUCCESS';
export const EXERCISE_DETAILS_REQUEST = 'EXERCISE_DETAILS_REQUEST';
export const EXERCISE_DETAILS_FAIL = 'EXERCISE_DETAILS_FAIL';

export const EXERCISE_DELETE_SUCCESS = 'EXERCISE_DELETE_SUCCESS;'
export const EXERCISE_DELETE_REQUEST = 'EXERCISE_DELETE_REQUEST;'
export const EXERCISE_DELETE_FAIL = 'EXERCISE_DELETE_FAIL;'

export const EXERCISE_ADD_SUCCESS = 'EXERCISE_ADD_SUCCESS;'
export const EXERCISE_ADD_REQUEST = 'EXERCISE_ADD_REQUEST;'
export const EXERCISE_ADD_FAIL = 'EXERCISE_ADD_FAIL;'
export const EXERCISE_ADD_RESET = 'EXERCISE_ADD_RESET;'

export const EXERCISE_UPDATE_SUCCESS = 'EXERCISE_UPDATE_SUCCESS;'
export const EXERCISE_UPDATE_REQUEST = 'EXERCISE_UPDATE_REQUEST;'
export const EXERCISE_UPDATE_FAIL = 'EXERCISE_UPDATE_FAIL;'
export const EXERCISE_UPDATE_RESET = 'EXERCISE_UPDATE_RESET;'